export const SEED_DATA = {
  pokemon: {
    name: "Pokémon",
    emoji: "⚡",
    color: "#FFCB05",
    gradient: "linear-gradient(135deg, #FFCB05 0%, #FF6B35 100%)",
    boxes: [
      {
        name: "Paldea Adventures",
        img: "🎴",
        items: [
          "Charizard ex",
          "Pikachu VMAX",
          "Mewtwo GX",
          "Eevee V",
          "Gengar VSTAR",
          "Rayquaza VMAX",
        ],
      },
      {
        name: "Scarlet & Violet",
        img: "🔴",
        items: [
          "Koraidon ex",
          "Miraidon ex",
          "Arcanine V",
          "Gardevoir ex",
          "Lucario VSTAR",
          "Tyranitar V",
        ],
      },
      {
        name: "Crown Zenith",
        img: "👑",
        items: [
          "Arceus VSTAR",
          "Giratina VSTAR",
          "Palkia VSTAR",
          "Dialga VSTAR",
          "Darkrai VSTAR",
          "Shaymin V",
        ],
      },
      {
        name: "Obsidian Flames",
        img: "🔥",
        items: [
          "Charizard ex SAR",
          "Dragonite V",
          "Tyranitar ex",
          "Groudon ex",
          "Blaziken VMAX",
          "Reshiram V",
        ],
      },
    ],
  },
  onepiece: {
    name: "One Piece",
    emoji: "🏴‍☠️",
    color: "#E63946",
    gradient: "linear-gradient(135deg, #E63946 0%, #FF006E 100%)",
    boxes: [
      {
        name: "Romance Dawn",
        img: "⛵",
        items: [
          "Luffy Gear 5 Leader",
          "Shanks SP",
          "Zoro Alt Art",
          "Nami SR",
          "Ace Manga Art",
          "Robin Parallel",
        ],
      },
      {
        name: "Paramount War",
        img: "⚔️",
        items: [
          "Whitebeard SP",
          "Akainu Leader",
          "Marco Alt Art",
          "Ace Fire Fist SR",
          "Blackbeard SP",
          "Sengoku SR",
        ],
      },
      {
        name: "Pillars of Strength",
        img: "💪",
        items: [
          "Kaido SP",
          "Big Mom Leader",
          "King Alt Art",
          "Queen SR",
          "Yamato SP",
          "Katakuri SR",
        ],
      },
      {
        name: "Wings of Captain",
        img: "🦅",
        items: [
          "Luffy SP",
          "Sanji Alt Art",
          "Zoro Enma SR",
          "Jinbe Leader",
          "Brook SR",
          "Franky Alt Art",
        ],
      },
    ],
  },
  jjk: {
    name: "Jujutsu Kaisen",
    emoji: "👁️",
    color: "#7B2FF7",
    gradient: "linear-gradient(135deg, #7B2FF7 0%, #C41CFF 100%)",
    boxes: [
      {
        name: "Cursed Clash",
        img: "💀",
        items: [
          "Gojo Domain Figure",
          "Sukuna Finger Set",
          "Yuji Action Pose",
          "Megumi Shikigami",
          "Nobara Hammer SR",
          "Todo Clap SP",
        ],
      },
      {
        name: "Shibuya Arc",
        img: "🌃",
        items: [
          "Awakened Sukuna",
          "Mahoraga Figure",
          "Jogo SR",
          "Mahito SP",
          "Choso Alt Art",
          "Toji Fushiguro SP",
        ],
      },
      {
        name: "Hidden Inventory",
        img: "🔮",
        items: [
          "Young Gojo SP",
          "Young Geto SR",
          "Toji SP",
          "Riko Figure",
          "Tengen SR",
          "Star Plasma Vessel Set",
        ],
      },
      {
        name: "Culling Game",
        img: "🎲",
        items: [
          "Maki Awakened SP",
          "Yuta SP",
          "Hakari SR",
          "Kashimo SP",
          "Kenjaku SR",
          "Angel Alt Art",
        ],
      },
    ],
  },
  gundam: {
    name: "Gundam",
    emoji: "🤖",
    color: "#00B4D8",
    gradient: "linear-gradient(135deg, #00B4D8 0%, #0077B6 100%)",
    boxes: [
      {
        name: "Universal Century",
        img: "🚀",
        items: [
          "RX-78-2 MG Ver.Ka",
          "Zaku II HG",
          "Nu Gundam RG",
          "Sazabi MG",
          "GP03 Dendrobium HG",
          "Unicorn PG",
        ],
      },
      {
        name: "Cosmic Era",
        img: "✨",
        items: [
          "Freedom MG 2.0",
          "Strike Rouge HG",
          "Justice RG",
          "Providence MG",
          "Destiny MG",
          "Akatsuki HG",
        ],
      },
      {
        name: "Iron-Blooded",
        img: "🔩",
        items: [
          "Barbatos Lupus Rex MG",
          "Grimgerde HG",
          "Vidar HG",
          "Bael MG",
          "Flauros HG",
          "Gusion Rebake HG",
        ],
      },
      {
        name: "Witch Mercury",
        img: "🧙",
        items: [
          "Aerial HG",
          "Pharact HG",
          "Lfrith HG",
          "Darilbalde HG",
          "Schwarzette HG",
          "Calibarn HG",
        ],
      },
    ],
  },
} as const;
